<?php

namespace ContainerRaUPlvc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInsertControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\InsertController' shared autowired service.
     *
     * @return \App\Controller\InsertController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/InsertController.php';

        $container->services['App\\Controller\\InsertController'] = $instance = new \App\Controller\InsertController(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\InsertController', $container));

        return $instance;
    }
}
