<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI8AQ0je\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI8AQ0je/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI8AQ0je.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI8AQ0je\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI8AQ0je\App_KernelDevDebugContainer([
    'container.build_hash' => 'I8AQ0je',
    'container.build_id' => 'a0c1befd',
    'container.build_time' => 1663601427,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI8AQ0je');
