<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container53XaWlY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container53XaWlY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container53XaWlY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container53XaWlY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container53XaWlY\App_KernelDevDebugContainer([
    'container.build_hash' => '53XaWlY',
    'container.build_id' => 'e743e009',
    'container.build_time' => 1664553140,
], __DIR__.\DIRECTORY_SEPARATOR.'Container53XaWlY');
