<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKb2havx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKb2havx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKb2havx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKb2havx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKb2havx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kb2havx',
    'container.build_id' => '0bb23de7',
    'container.build_time' => 1663691477,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKb2havx');
